# apiVersion: v1
# kind: Service
# metadata:
#   name: mywebapp
#   namespace: default
#   labels:
#     app: mywebapp
# spec:
#   ports:
#   - port: 80
#     protocol: TCP
#     name: flask
#   selector:
#     app: mywebapp
#     tier: frontend
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 3001
    protocol: TCP
    name: nodejs-api
  selector:
    app: {{ .Values.appName }}
    tier: backend
  type: NodePort
